name: Deploy to S3 on Push
on:
  push:
    branches:
      - “*”
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: echo branch name
        run: |
          echo ${{ github.ref_name }}
